development:
  adapter: mysql2
  database: gym_dev
  encoding: utf8
  username: root
  password: legenda
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: mysql2
  database: gym_test
  encoding: utf8
  username: root
  password: legenda
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: gym_prod
  encoding: utf8
  username: root
  password: legenda
  host: localhost
  pool: 5
  timeout: 5000
